version: '3.8' 

services:
    
  web: 
    build: ./docker-config/php
    container_name: app_php
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - mysql